### ISSUE TITLE
Shiny Express can now serve static files with v0.8.0

### ISSUE THREAD

**Issue by gadenbuie** [posit-dev/py-shiny-site#117]
https://shiny.posit.co/py/docs/ui-customize.html#serve-local-files

https://github.com/posit-dev/py-shiny-site/blob/429ace2e0f031998cd9a55bc16b06b4d8a9c82d6/docs/ui-customize.qmd#L226-L228

Reported on Discord: https://discord.com/channels/1109483223987277844/1112869981735104553/1214516951658004580

**Comment by wch** [comment]
Related to #113.
