### ISSUE TITLE
`value_box` and related docs have broken examples

### ISSUE THREAD

**Issue by phobson** [posit-dev/py-shiny-site#191]
It appears that icons.py has disappeared from the live examples of `value_box` and its ilk:

https://shiny.posit.co/py/api/core/ui.value_box.html#examples

![image](https://github.com/user-attachments/assets/2270092c-4a75-49e1-a7e8-2c680de46b6e)

**Comment by phobson** [comment]
Oops. Just saw this: https://github.com/posit-dev/py-shiny-site/issues/181

Sorry for the noise. Closing as redundant

**Comment by gadenbuie** [comment]
Thanks again, upstream issue is: https://github.com/posit-dev/py-shiny/issues/1568
