### ISSUE TITLE
NameError: name 'input_text' is not defined -> Tried to access `input`, but it was not imported. Perhaps you need `from shiny.express import input`?

### ISSUE THREAD

**Issue by shnonomura** [posit-dev/py-shiny-site#199]
Here’s a basic example of using a text output (reacting to changes in a text input):

from shiny.express import render, ui , **input**

ui.input_text("text", label="Enter some text")

@render.text
def text_out():
    return f"Input text: {input.text()}"

**Comment by wch** [comment]
Are you referring to the example on this page? https://shiny.posit.co/py/docs/ui-overview.html

**Comment by shnonomura** [comment]
yes.

**Comment by wch** [comment]
Thanks, I've fixed it in e3c4d78f25675e824396759f8519400bae8581ec.
