### ISSUE TITLE
page for modal_remove does not actually show how to use the function

### ISSUE THREAD

**Issue by athenadeng** [posit-dev/py-shiny-site#201]
on the page: https://shiny.posit.co/py/api/core/ui.modal_remove.html

the function ui.modal_remove() is never actually used on this page, even though the purpose of the example code is to show how it's being used.

**Comment by gadenbuie** [comment]
Thanks for the reminder @athenadeng! I had made a note of this in [a shiny issue](https://github.com/posit-dev/py-shiny/issues/1318#issuecomment-2059570999), but I think I was distracted by other aspects of that issue and adding the example to the docs fell off my radar.
