### ISSUE TITLE
In Shinylive "Testing whether a package is available" page, code should have `await`

### ISSUE THREAD

**Issue by wch** [posit-dev/py-shiny-site#4]
On https://shiny.posit.co/py/docs/shinylive.html#testing-whether-a-package-is-available, the code says this:

```
import micropip
micropip.install("mypackage")
import mypackage
```

But it should have an `await`, as in:

```
import micropip
await micropip.install("mypackage")
import mypackage
```

**Comment by joesho112358** [comment]
<img width="814" alt="image" src="https://github.com/posit-dev/py-shiny-site/assets/8650931/b4e3c160-00d8-417e-85e8-debb5dd16bc2">

@wch Looks like this can be closed
