### ISSUE TITLE
"Function Reference" page for `ui.tags`

### ISSUE THREAD

**Issue by youngroklee-ml** [posit-dev/py-shiny-site#67]
Hi, I originally submitted this issue to py-shiny repository, because I did not know there is this separate repository for website.
https://github.com/posit-dev/py-shiny/issues/1005#issue-2080391297

====

In the following links, the list of function description goes only up to "iframe", and many of the description shows just "Create a".
https://shiny.posit.co/py/api/ui.tags.html

![image](https://github.com/posit-dev/py-shiny/assets/30917347/fa5382d2-a4b3-48f1-af74-303bb1c799cb)

**Comment by joesho112358** [comment]
@youngroklee-ml Looks like this may have been fixed at some point

<img width="778" alt="image" src="https://github.com/posit-dev/py-shiny-site/assets/8650931/14465ea3-73ab-4df0-a374-757d11888572">

**Comment by gadenbuie** [comment]
Yup, we fixed this last week I believe. Sorry I missed this issue when I made the change!
