### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by joegurr** [posit-dev/py-shiny-site#91]
The link `<a href="https://shiny.posit.co/py/api/render.display.html">@render.display</a>` under `https://shiny.posit.co/py/components/outputs/ui/index.html#relevant-functions` is broken.

**Comment by gadenbuie** [comment]
Thanks for pointing this out! There was an issue with our redirects that I just fixed. Once the site redeploys (in about 10 minutes), the new redirect logic should make this link work as expected.

**Comment by joegurr** [comment]
Awesome, thanks @gadenbuie

**Comment by gadenbuie** [comment]
This should be fixed now, thanks again @joegurr!
